# Generated by Django 3.2.6 on 2023-08-17 14:03

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('client_area', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('about', models.TextField()),
                ('img', models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='apps/static/assets/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.home.models.custom_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='home.project')),
            ],
        ),
    ]
