# Generated by Django 3.2.6 on 2023-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default='others', max_length=100),
        ),
    ]
