# Generated by Django 4.2.5 on 2023-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_unit_bill_profile_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
