# Generated by Django 4.2.5 on 2023-11-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_client_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='title',
            new_name='name',
        ),
    ]
