# Generated by Django 4.2.5 on 2023-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completition',
            field=models.IntegerField(default=0),
        ),
    ]
