# Generated by Django 4.2.5 on 2023-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_title_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cpnj',
            new_name='cnpj',
        ),
    ]
