# Generated by Django 4.2.5 on 2023-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_cpnj_client_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='uploads/clients/avatar'),
        ),
    ]
