# Generated by Django 4.2.5 on 2023-11-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_client_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='cpnj',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='avatar',
            field=models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='uploads/units/avatar'),
        ),
        migrations.AddField(
            model_name='unit',
            name='location',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
