# Generated by Django 4.2.5 on 2023-11-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_cpnj_unit_cnpj_rename_title_unit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
    ]
