# Generated by Django 3.2.6 on 2023-09-14 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='apps/static/assets/uploads/profile_pics')),
                ('about', models.TextField(default='')),
                ('address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
