# Generated by Django 4.2.5 on 2023-11-14 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_bill_created_by_alter_bill_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='BillToReceive',
        ),
    ]
