# Generated by Django 4.2.5 on 2023-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_bill_billtoreceive'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtopay',
            name='method',
            field=models.CharField(default='others', max_length=100),
        ),
        migrations.AlterField(
            model_name='billtoreceive',
            name='number_of_installments',
            field=models.IntegerField(default=0),
        ),
    ]
