# Generated by Django 4.2.5 on 2023-11-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_billtopay_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtopay',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='billtoreceive',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
