<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-21 19:02
=======
# Generated by Django 4.2.5 on 2023-09-15 20:19
>>>>>>> 4d5f4486dfb71a5dab9bafd9e942cab04da50363

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_profile_education_remove_profile_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
