# Generated by Django 4.2.5 on 2023-11-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_billtoreceive_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtoreceive',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_to_receive', to='home.client'),
        ),
    ]
