# Generated by Django 4.2.5 on 2023-09-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_profile_education_remove_profile_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
