# Generated by Django 4.2.5 on 2023-11-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_billtoreceive_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtopay',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billtoreceive',
            name='status',
        ),
    ]
