# Generated by Django 4.2.5 on 2023-11-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_billtopay_status_remove_billtoreceive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtopay',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_to_pay', to='home.client'),
        ),
    ]
