# Generated by Django 4.2.5 on 2023-11-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_billtopay_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='avatar',
            field=models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='uploads/offices/avatar'),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('admission', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='home.unit')),
            ],
        ),
    ]
