# Generated by Django 4.2.5 on 2023-11-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_unit_avatar_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtopay',
            old_name='unit',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='billtoreceive',
            old_name='unit',
            new_name='office',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unit',
        ),
    ]
