# Generated by Django 4.2.5 on 2023-11-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_unit_billtopay_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.unit'),
        ),
    ]
