# Generated by Django 4.2.5 on 2023-11-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_profile_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='name',
        ),
    ]
