# Generated by Django 4.2.5 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_collaborator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
