# Generated by Django 4.2.5 on 2023-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_collaborator_first_name_collaborator_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='postal_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
