# Generated by Django 4.2.5 on 2023-11-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_collaborator_about_collaborator_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expiration', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('uploaded', models.DateField()),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='home.collaborator')),
            ],
        ),
    ]
