# Generated by Django 4.2.5 on 2023-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profile_bills_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bills_permission',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_permission',
            field=models.BooleanField(default=False),
        ),
    ]
