# Generated by Django 4.2.5 on 2023-12-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_profile_bills_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance_permission',
        ),
    ]
