# Generated by Django 4.2.5 on 2023-12-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_bill_client_alter_bill_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='home.client'),
        ),
    ]
