# Generated by Django 4.2.5 on 2023-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_uploadedfile_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
