# Generated by Django 4.2.5 on 2023-12-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_client_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='area',
        ),
    ]
