# Generated by Django 4.2.5 on 2023-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_office_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
