# Generated by Django 4.2.5 on 2023-12-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_uploadeddocument_file'),
        ('home', '0029_office_description'),
    ]

    operations = [
    ]
