# Generated by Django 4.2.5 on 2023-12-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.profile'),
        ),
    ]
