# Generated by Django 4.2.5 on 2023-12-19 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0034_remove_document_collab_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
