# Generated by Django 4.2.5 on 2024-01-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_address_profile_street_profile_street_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
    ]
