# Generated by Django 4.2.9 on 2024-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identification',
            field=models.IntegerField(default=0),
        ),
    ]
