# Generated by Django 4.2.9 on 2024-01-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_profile_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admission',
            new_name='aso',
        ),
    ]
