# Generated by Django 4.2.9 on 2024-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_admission_profile_aso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.IntegerField(default=0),
        ),
    ]
