# Generated by Django 4.2.9 on 2024-01-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_profile_admission_profile_cpf_profile_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registration',
        ),
    ]
