# Generated by Django 4.2.9 on 2024-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_profile_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
