# Generated by Django 4.2.9 on 2024-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_rename_email_client_xml_email_client_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
