# Generated by Django 4.2.9 on 2024-02-01 16:00

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_document_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.home.models.custom_upload_path_documents),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.home.models.custom_upload_path_projects),
        ),
    ]
