# Generated by Django 4.2.9 on 2024-02-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_document_file_alter_uploadedfile_file'),
        ('home', '0048_document_client'),
    ]

    operations = [
    ]
