# Generated by Django 4.2.9 on 2024-02-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_project_assigned_to_project_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='client_str',
        ),
    ]
