# Generated by Django 4.2.9 on 2024-02-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_area',
        ),
    ]
