# Generated by Django 4.2.9 on 2024-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_link_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.URLField(),
        ),
    ]
