# Generated by Django 4.2.9 on 2024-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_link_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
