# Generated by Django 4.2.10 on 2024-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='apps/static/assets/img/icons/custom/1x/placeholder.webp', upload_to='profile_pics'),
        ),
    ]
