# Generated by Django 4.2.10 on 2024-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='static/assets/img/icons/custom/1x/placeholder.webp', upload_to='project_pics'),
        ),
    ]
