# Generated by Django 4.2.10 on 2024-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', upload_to='uploads/clients/avatar'),
        ),
        migrations.AlterField(
            model_name='office',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', upload_to='uploads/offices/avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='placeholder.webp', upload_to='project_pics'),
        ),
    ]
