# Generated by Django 4.2.10 on 2024-03-11 16:30

import apps.home.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_client_avatar_alter_office_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', storage=apps.home.storage_backends.PrivateMediaStorage(), upload_to='profile_pics'),
        ),
    ]
