# Generated by Django 4.2.10 on 2024-03-11 16:44

import apps.home.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', storage=apps.home.storage_backends.PublicMediaStorage(), upload_to='profile_pics'),
        ),
    ]
