# Generated by Django 4.2.10 on 2024-03-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='qrcode',
            field=models.ImageField(default='placeholder.webp', upload_to='qrcodes/equipments/2024/'),
        ),
    ]
