# Generated by Django 4.2.10 on 2024-03-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home', '0064_alter_equipments_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authentication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authentication.authemail'),
        ),
    ]
