# Generated by Django 4.2.11 on 2024-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_rename_installments_bill_installments_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', upload_to='client_pics'),
        ),
    ]
