# Generated by Django 4.2.11 on 2024-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_alter_profile_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='billinstallment',
            name='payment_info',
            field=models.TextField(default=''),
        ),
    ]
