# Generated by Django 4.2.11 on 2024-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_bill_payment_info_billinstallment_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='installments_frequency',
            field=models.IntegerField(default=30),
        ),
    ]
