# Generated by Django 4.2.11 on 2024-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_bill_installments_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='installments_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
