# Generated by Django 4.2.11 on 2024-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_project_deadline_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
