# Generated by Django 4.2.11 on 2024-06-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_office_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='office',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='home.office'),
        ),
    ]
