# Generated by Django 4.2.14 on 2024-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
