# Generated by Django 4.2.14 on 2024-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_bankaccount_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
