# Generated by Django 4.2.14 on 2024-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_alter_bankaccount_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='pix',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
