# Generated by Django 4.2.14 on 2024-07-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_document_office'),
        ('home', '0091_alter_bankaccount_bank_code_and_more'),
    ]

    operations = [
    ]
