# Generated by Django 4.2.14 on 2024-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_office_duns_office_municipal_inscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='name',
            new_name='company_name',
        ),
    ]
