# Generated by Django 4.2.14 on 2024-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_rename_name_office_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='fantasy_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
