# Generated by Django 4.2.14 on 2024-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_bankaccount_office_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='pcmso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='pgr',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
