# Generated by Django 4.2.14 on 2024-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_office_pcmso_office_pgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='custom_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
