# Generated by Django 4.2.14 on 2024-08-07 12:31

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_uploadedfile_custom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_path_bills)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='home.bill')),
            ],
        ),
    ]
