# Generated by Django 4.2.14 on 2024-08-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_billproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='home.branch'),
        ),
        migrations.AlterField(
            model_name='billproof',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='home.bill'),
        ),
    ]
