# Generated by Django 4.2.14 on 2024-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_billproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
