# Generated by Django 4.2.15 on 2024-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_bill_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='authentication_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinstallment',
            name='authentication_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinstallment',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinstallment',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
