# Generated by Django 4.2.15 on 2024-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_bill_authentication_key_bill_invoice_bill_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='identification',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
