# Generated by Django 4.2.15 on 2024-12-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_client_identification_project_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='home.branch'),
        ),
    ]
