# Generated by Django 4.2.15 on 2025-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_project_client_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='identification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='qrcode',
            field=models.ImageField(default='placeholder.webp', upload_to='qrcodes/equipments/2025/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='identification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
