# Generated by Django 4.2.17 on 2025-01-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0105_branch_identification_alter_equipments_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name_plural': 'Equipments'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, choices=[(24, 'bankaccount'), (14, 'bill'), (20, 'billinstallment'), (25, 'billproof'), (21, 'branch'), (12, 'client'), (13, 'collaborator'), (16, 'document'), (7, 'equipments'), (17, 'link'), (22, 'meeting'), (15, 'office'), (11, 'profile'), (8, 'project'), (23, 'subtask'), (10, 'task'), (9, 'uploadedfile')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
