# Generated by Django 4.2.22 on 2025-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_alter_bill_partial_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cnpj',
            field=models.CharField(default='', max_length=14),
        ),
    ]
