# Generated by Django 4.2.17 on 2025-01-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_alter_equipments_options_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billinstallment',
            options={'verbose_name': 'Bill Installment', 'verbose_name_plural': 'Bill Installments'},
        ),
        migrations.AlterModelOptions(
            name='billproof',
            options={'verbose_name': 'Bill Proof', 'verbose_name_plural': 'Bill Proofs'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Client Branch', 'verbose_name_plural': 'Client Branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': 'SubTask', 'verbose_name_plural': 'SubTasks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
    ]
