# Generated by Django 4.2.22 on 2025-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_profile_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='placeholder.webp', upload_to='profile_pics'),
        ),
    ]
