# Generated by Django 4.2.17 on 2025-01-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0107_alter_bankaccount_options_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, choices=[('bankaccount', 'bankaccount'), ('bill', 'bill'), ('billinstallment', 'billinstallment'), ('billproof', 'billproof'), ('branch', 'branch'), ('client', 'client'), ('collaborator', 'collaborator'), ('document', 'document'), ('equipments', 'equipments'), ('link', 'link'), ('meeting', 'meeting'), ('office', 'office'), ('profile', 'profile'), ('project', 'project'), ('subtask', 'subtask'), ('task', 'task'), ('uploadedfile', 'uploadedfile')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
