# Generated by Django 4.2.17 on 2025-01-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0108_alter_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, choices=[(24, 'bankaccount'), (14, 'bill'), (20, 'billinstallment'), (25, 'billproof'), (21, 'branch'), (12, 'client'), (13, 'collaborator'), (16, 'document'), (7, 'equipments'), (17, 'link'), (22, 'meeting'), (15, 'office'), (11, 'profile'), (8, 'project'), (23, 'subtask'), (10, 'task'), (9, 'uploadedfile')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
