# Generated by Django 4.2.17 on 2025-01-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0109_alter_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'home', 'model__not': 'category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
