# Generated by Django 4.2.17 on 2025-01-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0110_alter_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('model', 'category'), _negated=True), ('app_label', 'home')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
