# Generated by Django 4.2.17 on 2025-01-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='foreignkey_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='home.category'),
        ),
        migrations.AddField(
            model_name='bill',
            name='foreignkey_subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='home.subcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='foreignkey_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='home.category'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='foreignkey_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='home.category'),
        ),
    ]
